version: '3.1'

services:

  app:
    build: .
    container_name: api
    ports:
      - '8000:8000'
    environment:
      DB_URL: 'postgresql+psycopg2://root:password@db/fastapi'
      DB_TEST_URL: 'postgresql+psycopg2://root:password@db/fastapitest'
    links:
      - db

  db:
    image: postgres
    restart: always
    container_name: db
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      POSTGRES_DB: fastapi
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - '5432:5432'

  adminer:
    image: adminer
    restart: always
    container_name: adminer
    ports:
      - '8080:8080'